### ISSUE TITLE
Importing modi raises a RuntimeError

### ISSUE THREAD

**Issue by dajeong012** [LUXROBO/pyMODI#117]
* pyMODI version: 0.7.1
* Python version: 3.7.4
* Operating System: macOS Catalina

### Description

When I import modi, it raises a RuntimeError.
One solution I got from Stackoverflow was to write the following code before I import modi.
```
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
```

### What I Did

```
import modi

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dajungpark/Repos/pyMODI/modi/__init__.py", line 3, in <module>
    from modi.modi import MODI
  File "/Users/dajungpark/Repos/pyMODI/modi/modi.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/Users/dajungpark/opt/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/dajungpark/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "/Users/dajungpark/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

**Comment by dajeong012** [comment]
This issue was found out to be irrelevant with pymodi.
The same error was raised even when importing pyplot solely.
```
pip uninstall matplotlib
python -m pip install matplotlib
```

**Comment by dajeong012** [comment]
This issue was found out to be irrelevant to pymodi.
The same error was raised even when importing pyplot solely.
```
pip uninstall matplotlib
python -m pip install matplotlib
```
